
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "coursera"
    ports:
      - "3307:3306"
    volumes:
      - ./sample_db.sql:/docker-entrypoint-initdb.d/10_sample.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p1234 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    profiles: [ "app" ]   # добавь эту строку
    build: .
    container_name: db_explorer
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DSN=root:1234@tcp(mysql:3306)/coursera?parseTime=true&charset=utf8mb4
    ports:
      - "8080:8080"
